# Generated by Django 2.2.7 on 2019-12-19 13:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number should be of 10 digits.', regex='^[1-9]\\d{9}$')])),
                ('payment_status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORDERID', models.CharField(max_length=30)),
                ('TXNID', models.CharField(max_length=64)),
                ('BANKTXNID', models.CharField(blank=True, max_length=100, null=True)),
                ('TXNAMOUNT', models.CharField(max_length=10)),
                ('CURRENCY', models.CharField(blank=True, max_length=4, null=True)),
                ('STATUS', models.CharField(max_length=12)),
                ('RESPCODE', models.CharField(max_length=10)),
                ('RESPMSG', models.TextField(max_length=250)),
                ('TXNDATE', models.DateTimeField(default=django.utils.timezone.now)),
                ('GATEWAYNAME', models.CharField(blank=True, max_length=30, null=True)),
                ('BANKNAME', models.CharField(blank=True, max_length=50, null=True)),
                ('PAYMENTMODE', models.CharField(blank=True, max_length=10, null=True)),
                ('MID', models.CharField(max_length=40)),
                ('TXNTYPE', models.CharField(blank=True, max_length=5, null=True)),
                ('REFUNDAMT', models.CharField(blank=True, max_length=10, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='paytm.PersonInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='paytm.PersonInfo')),
            ],
        ),
    ]
