# Generated by Django 2.2.7 on 2019-11-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytm', '0002_auto_20191119_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playersinfo',
            old_name='leader',
            new_name='leader_username',
        ),
        migrations.AddField(
            model_name='playersinfo',
            name='team_leader_fullname',
            field=models.CharField(default='voldemort', max_length=100),
            preserve_default=False,
        ),
    ]
