# Generated by Django 2.2.7 on 2019-11-19 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paytm', '0003_auto_20191119_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playersinfo',
            old_name='leader_username',
            new_name='leader_fullname',
        ),
        migrations.RenameField(
            model_name='playersinfo',
            old_name='participant_1',
            new_name='member_1',
        ),
        migrations.RenameField(
            model_name='playersinfo',
            old_name='participant_2',
            new_name='member_2',
        ),
        migrations.RenameField(
            model_name='playersinfo',
            old_name='participant_3',
            new_name='member_3',
        ),
        migrations.RenameField(
            model_name='playersinfo',
            old_name='team_leader_fullname',
            new_name='member_4',
        ),
    ]
